- name: Check for Fuseki
  stat:
    path: "{{ target_dir }}/systems/fuseki/apache-jena-fuseki-{{ fuseki_version }}/"
  register: fuseki_dir

- block:
  - name: Create Fuseki directory
    file:
      path: "{{ target_dir }}/systems/fuseki"
      state: directory

  - name: Create a temporary download directory
    tempfile:
      state: directory
      suffix: fuseki
    register: tempdir

  - name: Download Fuseki Checksum
    get_url:
      url: https://archive.apache.org/dist/jena/binaries/apache-jena-fuseki-{{ fuseki_version }}.tar.gz.sha512
      dest: "{{ tempdir.path }}/apache-jena-fuseki-{{ fuseki_version }}.tar.gz.sha512"

  - name: Slurp Fuseki Checksum
    slurp:
      path: "{{ tempdir.path }}/apache-jena-fuseki-{{ fuseki_version }}.tar.gz.sha512"
    register: checksum

  - name: Download Fuseki
    get_url:
      url: https://archive.apache.org/dist/jena/binaries/apache-jena-fuseki-{{ fuseki_version }}.tar.gz
      checksum: "sha512:{{ (checksum.content | b64decode).split(' ')[0] }}"
      dest: "{{ tempdir.path }}/apache-jena-fuseki-{{ fuseki_version }}.tar.gz"

  - name: Unzip Fuseki
    unarchive:
      remote_src: yes
      src: "{{ tempdir.path }}/apache-jena-fuseki-{{ fuseki_version }}.tar.gz"
      dest: "{{ target_dir }}/systems/fuseki"

  - name: Delete tempdir
    file:
      path: "{{ tempdir.path }}"
      state: absent

  - name: Ensure Fuseki is executable
    file:
      path: "{{ target_dir }}/systems/fuseki/apache-jena-fuseki-{{ fuseki_version }}/fuseki-server"
      mode: 0755
  when: not fuseki_dir.stat.exists
